// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-LG1mttCLQ7zSLlg6f5fawTmY37JgL0U',
    appId: '1:187466581100:web:5c1d5748b7941937914449',
    messagingSenderId: '187466581100',
    projectId: 'chat-ai-d2c8c',
    authDomain: 'chat-ai-d2c8c.firebaseapp.com',
    storageBucket: 'chat-ai-d2c8c.firebasestorage.app',
    measurementId: 'G-RLV6X8K1VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCspmf_j6_SewUn6bfCmtMdK0tckRGATMA',
    appId: '1:187466581100:android:3e69c557daa4bce3914449',
    messagingSenderId: '187466581100',
    projectId: 'chat-ai-d2c8c',
    storageBucket: 'chat-ai-d2c8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCew-AcfaYg0YGvk12gVtX3Gn-AHAzQYJE',
    appId: '1:187466581100:ios:13d0f4c6aff55b34914449',
    messagingSenderId: '187466581100',
    projectId: 'chat-ai-d2c8c',
    storageBucket: 'chat-ai-d2c8c.firebasestorage.app',
    iosClientId: '187466581100-j44t0ngu4tpmeg6j391fus6mmjvi5r5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.loveChatSimulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCew-AcfaYg0YGvk12gVtX3Gn-AHAzQYJE',
    appId: '1:187466581100:ios:13d0f4c6aff55b34914449',
    messagingSenderId: '187466581100',
    projectId: 'chat-ai-d2c8c',
    storageBucket: 'chat-ai-d2c8c.firebasestorage.app',
    iosClientId: '187466581100-j44t0ngu4tpmeg6j391fus6mmjvi5r5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.loveChatSimulator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-LG1mttCLQ7zSLlg6f5fawTmY37JgL0U',
    appId: '1:187466581100:web:7aab31c3f2ebcfae914449',
    messagingSenderId: '187466581100',
    projectId: 'chat-ai-d2c8c',
    authDomain: 'chat-ai-d2c8c.firebaseapp.com',
    storageBucket: 'chat-ai-d2c8c.firebasestorage.app',
    measurementId: 'G-CHCH08PZGN',
  );
}
